admin:
  resource: "@AdminBundle/Resources/config/routing.yml"
  prefix:   /admin

user:
  resource: '@UserBundle/Resources/config/routing.yml'

frontend:
  resource: '@FrontendBundle/Resources/config/routing.yml'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
