<?php

namespace AdminBundle\Entity\Repository;

use AdminBundle\Entity\Advt;
use Doctrine\ORM\EntityRepository;

/**
 * AdvtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvtRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function getSimpleQuery()
    {
        return $this->createQueryBuilder('Advt')
            ->orderBy('Advt.id', 'DESC')
            ->getQuery();
    }
}
