<?php

namespace UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildRepository extends EntityRepository
{

    /**
     * KidsForRemove.
     *
     * @param array   $array    Id kids for remove.
     * @param integer $fatherId Father Id.
     *
     * @return array
     */
    public function kidsForRemove(array $array, $fatherId)
    {
        if (empty($array)) {
            return [];
        }
        $count = 1;
        $query = $this->createQueryBuilder('Child')
            ->where('Child.id != :child1');
        foreach ($array as $child) {
            if ($count != 1) {
                $query = $query->andWhere('Child.id != :child' . $count);
            }
            $count++;
        };
        $query = $query->andWhere('Child.father = :fatherId');
        $count = 1;
        $query = $query->setParameter(':child1', $array[0]);
        foreach ($array as $child) {
            if ($count != 1) {
                $query = $query->setParameter(':child' . $count, $child);
            }
            $count++;
        };
        $query = $query->setParameter(':fatherId', $fatherId);

        return $query->getQuery()->getResult();
    }
}
